name: "Workflow: Master branch"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  assemble: 
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run Gradle task
        run: >-
          ./gradlew :app:assembleDebug
          --daemon
          -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx1g"
